qbittorrent:
  network:
    web_port: 30000
    bt_port: 32555
    host_network: true
  run_as:
    user: 1000
    group: 1000
  storage:
    downloads:
      type: hostPath
      hostPath: /mnt/{{ .Release.Namespace }}/downloads
      datasetName: ""
    config:
      type: hostPath
      hostPath: /mnt/{{ .Release.Namespace }}/config
      datasetName: ""
