appVolumeMounts:
  data:
    emptyDir: true
    mountPath: /app/config
  identity:
    emptyDir: true
    mountPath: /app/identity
authToken: user:sasjkadkjhakdlaskdlkajsd
dnsConfig:
  options: []
domainAddress: localhost
email: user@example.com
emptyDirVolumes: true
environmentVariables: []
extraAppVolumeMounts: []
identityCreationMountPath: /root/.local/share/storj/identity/storagenode
image:
  pullPolicy: IfNotPresent
  repository: storjlabs/storagenode
  tag: 1d42f9ac3-v1.68.2-go1.18.8
nodePort: 30002
runAsGroup: 568
runAsUser: 568
storageSize: 500
wallet: 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
webPort: 30000
global: {}
use_ci_values: true
ci_ca_cert: -----BEGIN CERTIFICATE-----\nMIIBbzCCARWgAwIBAgIQCYtUyF4iIoFhygxySNuBUTAKBggqhkjOPQQDAjAQMQ4w\nDAYDVQQKEwVTdG9yajAiGA8wMDAxMDEwMTAwMDAwMFoYDzAwMDEwMTAxMDAwMDAw\nWjAQMQ4wDAYDVQQKEwVTdG9yajBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABINU\nbmV0hoE2MsI90HtpCajLcL8yi8dxKneVRRZmy7ngJeFU8tXFt58ZfGG7So9TQ9f5\nj5MKGRStRUrTjgBuO/+jTTBLMA4GA1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTAD\nAQH/MB0GA1UdDgQWBBSPDrtZrvwu5k76rzclB3D4S1ziTjAJBgSINwIBBAEAMAoG\nCCqGSM49BAMCA0gAMEUCIQDI98nktPLv/l8FV7XBPOzsp8UGMtGUC1BSmSFCeNA4\nAgIgeSarmxqtayyEeK9YwUOwfrN7+YuiwLPRxqY1PET/2ME=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIBWzCCAQGgAwIBAgIRAK7f/E+PDEvB/TrUSaHxOEYwCgYIKoZIzj0EAwIwEDEO\nMAwGA1UEChMFU3RvcmowIhgPMDAwMTAxMDEwMDAwMDBaGA8wMDAxMDEwMTAwMDAw\nMFowEDEOMAwGA1UEChMFU3RvcmowWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATr\nsDBAh7sr9eVZJUIFb79WK2qTcSKw/sP95JF5rCIJ5FvvwA/cx70VdW6IQjVhIaDY\nllQONAD90PeoOpqSyo+iozgwNjAOBgNVHQ8BAf8EBAMCAgQwEwYDVR0lBAwwCgYI\nKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiEAzPdn\n5ZK9hIUm+0b7iBHfk1T/O7gpwGTmsSLps4cF6KgCIDhgQ4g2givMj5Khmuhnr/e7\nz6HlDVf3PJOQv1yZqg7W\n-----END CERTIFICATE-----\n
ci_identity_cert: -----BEGIN CERTIFICATE-----\nMIIBYjCCAQigAwIBAgIRAJVNj2GWmfmJ1cGLAoNTW4owCgYIKoZIzj0EAwIwEDEO\nMAwGA1UEChMFU3RvcmowIhgPMDAwMTAxMDEwMDAwMDBaGA8wMDAxMDEwMTAwMDAw\nMFowEDEOMAwGA1UEChMFU3RvcmowWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARR\nQpyfAW95nFrCNfueSIHTHO/A7LG1JBbKc/df2Bcl5f5or1pPYKt76/VdKcgyGMe1\nrPO8CN0nWSFiLazSS0UIoz8wPTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYI\nKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDSAAw\nRQIgQiUltnY7/VloQM3Q5KptdebtXigWGT0QcnrdeUxqI2cCIQCe7AuB1Njoap/U\nhQf43mQh595FcUvw8nmWDhcgE4k6OA==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIBbzCCARWgAwIBAgIQCYtUyF4iIoFhygxySNuBUTAKBggqhkjOPQQDAjAQMQ4w\nDAYDVQQKEwVTdG9yajAiGA8wMDAxMDEwMTAwMDAwMFoYDzAwMDEwMTAxMDAwMDAw\nWjAQMQ4wDAYDVQQKEwVTdG9yajBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABINU\nbmV0hoE2MsI90HtpCajLcL8yi8dxKneVRRZmy7ngJeFU8tXFt58ZfGG7So9TQ9f5\nj5MKGRStRUrTjgBuO/+jTTBLMA4GA1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTAD\nAQH/MB0GA1UdDgQWBBSPDrtZrvwu5k76rzclB3D4S1ziTjAJBgSINwIBBAEAMAoG\nCCqGSM49BAMCA0gAMEUCIQDI98nktPLv/l8FV7XBPOzsp8UGMtGUC1BSmSFCeNA4\nAgIgeSarmxqtayyEeK9YwUOwfrN7+YuiwLPRxqY1PET/2ME=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIBWzCCAQGgAwIBAgIRAK7f/E+PDEvB/TrUSaHxOEYwCgYIKoZIzj0EAwIwEDEO\nMAwGA1UEChMFU3RvcmowIhgPMDAwMTAxMDEwMDAwMDBaGA8wMDAxMDEwMTAwMDAw\nMFowEDEOMAwGA1UEChMFU3RvcmowWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATr\nsDBAh7sr9eVZJUIFb79WK2qTcSKw/sP95JF5rCIJ5FvvwA/cx70VdW6IQjVhIaDY\nllQONAD90PeoOpqSyo+iozgwNjAOBgNVHQ8BAf8EBAMCAgQwEwYDVR0lBAwwCgYI\nKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiEAzPdn\n5ZK9hIUm+0b7iBHfk1T/O7gpwGTmsSLps4cF6KgCIDhgQ4g2givMj5Khmuhnr/e7\nz6HlDVf3PJOQv1yZqg7W\n-----END CERTIFICATE-----\n
ci_identity_key: -----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgVp+SZ2IcVZvJqlyZ\n9P6tE1JQyTxK7l4nHHEPq5ZzE96hRANCAARRQpyfAW95nFrCNfueSIHTHO/A7LG1\nJBbKc/df2Bcl5f5or1pPYKt76/VdKcgyGMe1rPO8CN0nWSFiLazSS0UI\n-----END PRIVATE KEY-----\n
