image:
  repository: ghcr.io/onedr0p/qbittorrent
  pullPolicy: IfNotPresent
  tag: 4.5.2

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

qbittorrent:
  network:
    webPort: 30000
    btPort: 50413
    hostNetwork: false
  runAs:
    user: 568
    group: 568
  storage:
    downloads:
      type: ixVolume
      hostPath: ""
      datasetName: downloads
    config:
      type: ixVolume
      hostPath: ""
      datasetName: config

notes:
  custom: |
    Default credentials:
    -  username: admin
    -  password: adminadmin
