# When inside the versioned minio folder, run:
# helm dependency update
# helm template -f ix_values.yaml -f ci/basic-values.yaml .

# Always use a unique hostPath for each test

minio:
  creds:
    rootUser: minio_test
    rootPass: minio_test
  multiMode:
    - /data{1...4}
  storage:
    - type: hostPath
      hostPath: /mnt/{{ .Release.Namespace }}/data1
      datasetName: ""
      mountPath: /data1
    - type: hostPath
      hostPath: /mnt/{{ .Release.Namespace }}/data2
      datasetName: ""
      mountPath: /data2
    - type: hostPath
      hostPath: /mnt/{{ .Release.Namespace }}/data3
      datasetName: ""
      mountPath: /data3
    - type: hostPath
      hostPath: /mnt/{{ .Release.Namespace }}/data4
      datasetName: ""
      mountPath: /data4
