image:
  repository: minio/minio
  tag: RELEASE.2023-02-22T18-23-45Z
  pullPolicy: IfNotPresent

imageLogsearch:
  repository: minio/operator
  tag: v4.5.8
  pullPolicy: IfNotPresent

imagePostgres:
  repository: postgres
  tag: "15.2"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

minio:
  creds:
    rootUser: ""
    rootPass: ""
  network:
    apiPort: 30000
    webPort: 30001
    certificateID: ""
    hostNetwork: false
    serverUrl: ""
    consoleUrl: ""
  logging:
    anonymous: false
    quiet: false
  multiMode: []
  storage: []

logsearch:
  enabled: false
  diskCapacityGB: 5
  storage:
    pgData:
      type: ixVolume
      hostPath: ""
      datasetName: postgres-data
    pgBackup:
      type: ixVolume
      hostPath: ""
      datasetName: postgres-backup

iXPortals:
  - portalName: "portal-from-values"
    protocol: "https"
    useNodeIP: true
    port: 30000
    path: "/"
