{{ $values := (. | mustDeepCopy) }}
{{ $_ := set $values "common" (dict "nameSuffix" "postgres") }}
{{ include "common.deployment.common_config" $values | nindent 0 }}
spec: {{ include "common.deployment.common_spec" $values | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" $values | nindent 4 }}
    spec:
      {{- if hasKey .Values.global "ixChartContext" }}
        {{- if .Values.global.ixChartContext.addNvidiaRuntimeClass }}
      runtimeClassName: {{ .Values.global.ixChartContext.nvidiaRuntimeClassName }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-postgres
        image: {{ template "postgres.imageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: {{ include "postgres.envVariableConfiguration" $values | nindent 10 }}
        volumeMounts: {{ include "postgres.volumeMountsConfiguration" $values | nindent 10 }}
        ports:
        - name: postgres-tcp
          containerPort: 5432
          protocol: TCP
      volumes: {{ include "postgres.volumeConfiguration" $values | nindent 8 }}
