{{- define "minio.configuration" -}}

  {{/* Validation */}}
  {{ include "minio.validation" $ }}

  {{ $config := fromJson (include "minio.prepare.config" $) }}

{{/* Secrets */}}
secret:
  minio-creds:
    enabled: true
    data:
      MINIO_ROOT_USER: {{ .Values.minio.creds.rootUser }}
      MINIO_ROOT_PASSWORD: {{ .Values.minio.creds.rootPass }}
      MINIO_VOLUMES: {{ $config.volumes }}
      {{ with .Values.minio.network.serverUrl }}
      MINIO_SERVER_URL: {{ . | quote }}
      {{ end }}
      {{ with .Values.minio.network.consoleUrl }}
      MINIO_BROWSER_REDIRECT_URL: {{ . | quote }}
      {{ end }}
      {{ if .Values.logsearch.enabled }}
      MINIO_AUDIT_WEBHOOK_ENABLE_ix_logsearch: "on"
      MINIO_AUDIT_WEBHOOK_ENDPOINT_ix_logsearch: {{ $config.webhookURL }}
      MINIO_LOG_QUERY_AUTH_TOKEN: {{ $config.queryToken }}
      MINIO_LOG_QUERY_URL: {{ $config.logQueryURL }}
      {{ end }}

  # Always create the logsearch and postgres secret, even if logsearch is disabled.
  # Because autogenerated passwords are stored in the secret, and disabling logsearch after
  # the secret is created will cause the passwords to be lost (if the secret is conditionally rendered).
  logsearch-creds:
    enabled: true
    data:
      LOGSEARCH_PG_CONN_STR: {{ $config.postgresURL }}
      LOGSEARCH_AUDIT_AUTH_TOKEN: {{ $config.auditToken }}
      MINIO_LOG_QUERY_AUTH_TOKEN: {{ $config.queryToken }}
      {{ if .Values.logsearch.enabled }}
      LOGSEARCH_DISK_CAPACITY_GB: {{ $config.diskCapacity | quote }}
      {{ end }}

  postgres-creds:
    enabled: true
    data:
      POSTGRES_PASSWORD: {{ $config.dbPass }}
      POSTGRES_USER: {{ $config.dbUser }}
      POSTGRES_DB: {{ $config.dbName }}
      POSTGRES_HOST: {{ $config.dbHost }}
      POSTGRES_URL: {{ $config.postgresURL }}

{{/* MinIO Certificate */}}
{{ if .Values.minio.network.certificateID }}
scaleCertificate:
  minio-cert:
    enabled: true
    labels: {}
    annotations: {}
    id: {{ .Values.minio.network.certificateID }}
{{ end }}

{{- end -}}
